baseURL = 'https://chakawelkin.github.io/'
languageCode = 'zh-cn'
title = '我的博客'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowWordCount = true
  ShowFullTextinRSS = true
  # 启用搜索功能
  [params.search]
    enabled = true
    # 搜索索引文件路径
    index = "search.json"
    # 搜索结果显示数量
    maxResults = 10
    # 搜索高亮显示
    highlight = true
    # 搜索匹配阈值（0-1之间，越小越精确）
    threshold = 0.3

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 40
