baseURL = "https://chakawelkin.github.io/"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"

# 网站标题
title = "ChakaBlog"

# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# 语言名称 ["English", "简体中文", "Français", "Polski", ...]
languageName = "简体中文"
# 是否包括中日韩文字
hasCJKLanguage = true

# 设置默认的语言 ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "zh-cn"

# 菜单配置
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    title = "文章"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    title = "标签"
  [[menu.main]]
    weight = 3
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    title = "分类"

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

# 网站输出配置，用于搜索功能
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  # 网站作者
  author = "Chaka"
  # 网站描述
  description = "Chaka 的个人博客"
  # 网站主页信息
  [params.home]
    # 主页简介
    [params.home.profile]
      enable = true
      title = "ChakaBlog"
      subtitle = "一个由 Hugo 和 LoveIt 驱动的个人博客。"
      typeit = true
      avatarURL = "/images/avatar.png" # 你的头像图片路径
      brand = ""
    # 主页文章列表
    [params.home.posts]
      enable = true
      paginate = 6 # 每页文章数
      defaultPaginate = true # 默认分页
      showAll = false # 是否显示所有文章，无论草稿状态
      # 主要文章排序
      # "Recent" || "Popular" || "Original"
      # primaryPostOrdering = "Recent"

  # 页脚设置
  [params.footer]
    enable = true
    # 是否显示"由 Hugo 强力驱动"
    powered = false
    # 是否显示主题信息
    theme = false

  # 搜索配置
  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 50
    highlightTag = "em"
    absoluteURL = false

# 多语言配置
[languages.zh-cn]
  weight = 2
  title = "ChakaBlog"
  languageCode = "zh-CN"
  languageName = "简体中文"
  hasCJKLanguage = true
  [languages.zh-cn.menu.main]
    weight = 1
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    title = "文章"
  [languages.zh-cn.menu.main]
    weight = 2
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    title = "标签"
  [languages.zh-cn.menu.main]
    weight = 3
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    title = "分类"
