baseURL = 'https://chakawelkin.github.io/'
languageCode = 'zh-cn'
title = '我的博客'
theme = 'PaperMod'

# 添加默认内容语言
defaultContentLanguage = 'zh-cn'
defaultContentLanguageInSubdir = false

# 添加输出格式配置
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowWordCount = true
  ShowFullTextinRSS = true
  # 禁用首页欢迎模块
  ShowHomeInfo = false
  # 启用搜索功能
  [params.search]
    enabled = true
    # 搜索索引文件路径
    index = "search.json"
    # 搜索结果显示数量
    maxResults = 10
    # 搜索高亮显示
    highlight = true
    # 搜索匹配阈值（0-1之间，越小越精确）
    threshold = 0.3

  # 文章列表样式
  [params.list]
    # 显示文章摘要
    ShowSummary = true
    # 显示阅读时间
    ShowReadingTime = true
    # 显示文章日期
    ShowDate = true
    # 显示文章作者
    ShowAuthor = false
    # 显示文章字数
    ShowWordCount = true
    # 显示文章分类
    ShowCategories = true
    # 显示文章标签
    ShowTags = true

  # 文章页面样式
  [params.page]
    # 显示文章目录
    ShowToc = true
    # 显示文章分享按钮
    ShowShareButtons = true
    # 显示文章导航
    ShowPostNavLinks = true
    # 显示文章面包屑
    ShowBreadCrumbs = true
    # 显示文章字数
    ShowWordCount = true
    # 显示文章阅读时间
    ShowReadingTime = true
    # 显示文章作者
    ShowAuthor = false
    # 显示文章日期
    ShowDate = true
    # 显示文章分类
    ShowCategories = true
    # 显示文章标签
    ShowTags = true

  # 时间格式配置
  [params.format]
    date = "2006年01月02日"
    lastmod = "2006年01月02日"
    readingTime = "预计阅读 %d 分钟"

  # 隐藏主题信息
  [params.footer]
    since = 2024
    customText = ""
    powered = false
    theme = false

  ShowFooter = false
  ShowPoweredBy = false
  ShowThemeInfo = false

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 40
