baseURL = 'https://chakawelkin.github.io/'
languageCode = 'zh-CN'
title = 'ExflyBlog'
theme = 'LoveIt'
hasCJKLanguage = true
defaultContentLanguage = 'zh-cn'
defaultContentLanguageInSubdir = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  defaultTheme = "auto"
  gitRepo = "https://github.com/chakawelkin/chakawelkin.github.io"
  dateFormat = "2006-01-02"
  title = "ExflyBlog"
  description = "ExflyBlog, IT technology sharing, technology blog"

  [params.author]
    name = "exfly"
    email = "exflyg@gmail.com"
    link = "https://github.com/exfly"

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = "ExflyBlog"
      pre = "<i class='far fa-kiss-wink-heart fa-fw' aria-hidden='true'></i>"
      post = ""
      typeit = true

  [params.footer]
    enable = true
    custom = ""
    hugo = true
    copyright = true
    author = true
    since = 2019
    icp = ""
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.search]
    enable = true
    type = "algolia"
    contentLength = 4000
    placeholder = "搜索文章标题或内容..."
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = "index.zh-cn"
      appID = "PASDMWALPK"
      searchKey = "b42948e51daaa93df92381c8e2ac0f93"

  [params.home]
    [params.home.profile]
      enable = true
      gravatar = ""
      avatarURL = "/media/img/avatar.jpg"
      title = "ExflyBlog"
      subtitle = "Keep It Simple & Stupid."
      typeit = true
      social = true
      cv = ""
    [params.home.posts]
      enable = true
      paginate = 6

[languages.zh-cn]
  weight = 1
  languageCode = "zh-CN"
  languageName = "简体中文"
  hasCJKLanguage = true
  contentDir = "content"

  [languages.zh-cn.menu]
    [[languages.zh-cn.menu.main]]
      identifier = "posts"
      name = "所有文章"
      url = "/posts/"
      weight = 10
    [[languages.zh-cn.menu.main]]
      identifier = "tags"
      name = "标签"
      url = "/tags/"
      weight = 20
    [[languages.zh-cn.menu.main]]
      identifier = "about"
      name = "关于"
      url = "/about/"
      weight = 30
    [[languages.zh-cn.menu.main]]
      identifier = "github"
      name = ""
      url = "https://github.com/exfly"
      pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
      target = "_blank"
      rel = "noopener noreffer"
      weight = 40
    [[languages.zh-cn.menu.main]]
      identifier = "search"
      name = ""
      url = "javascript:void(0);"
      pre = "<i class='fas fa-search fa-fw' aria-hidden='true'></i>"
      weight = 50
    [[languages.zh-cn.menu.main]]
      identifier = "theme-switch"
      name = ""
      url = "javascript:void(0);"
      pre = "<i class='fas fa-adjust fa-fw' aria-hidden='true'></i>"
      weight = 60
    [[languages.zh-cn.menu.main]]
      identifier = "language"
      name = ""
      url = "javascript:void(0);"
      pre = "<i class='fa fa-globe' aria-hidden='true'></i>"
      weight = 70
