baseURL = "https://chakawelkin.github.io/"

[params.page.comment]
  enable = true

[params.page.comment.giscus]
  enable = true
  repo = "chakawelkin/chakawelkin.github.io"
  repoId = "R_kgDOO5ys_g"
  category = "General"
  categoryId = "DIC_kwDOO5ys_s4CrcSH"
  mapping = "pathname"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  lightTheme = "light"
  darkTheme = "dark"
  lazyLoading = false